services:
    
    sonata.admin.user.user:
        class: Sinenco\UserBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Users", label: "Users" }
        arguments:
            - ~
            - Sinenco\UserBundle\Entity\User
            - ~
        calls:
            - [ setTranslationDomain, [SinencoUserBundle]]
            