# @Sinenco//UserBundle/Resources/config/services.yml

services:
    sinenco_user.registration.form.type:
        class: Sinenco\UserBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: sinenco_user_registration }
            
    sinenco_user.mailer:
        class: Sinenco\UserBundle\Mailer\UserMailer
        arguments: 
            container: "@service_container"
            
    sonata.block.user:
        class: Sinenco\UserBundle\Admin\UserBlock
        tags:
            - { name: sonata.block }
        arguments: [sonata.block.service.rss, '@templating', @doctrine.orm.entity_manager]