<?php

namespace Sinenco\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository {

    public function count() {
        return $this->createQueryBuilder('a')
                        ->select('COUNT(a)')
                        ->getQuery()
                        ->getSingleScalarResult();
    }

    public function findProductsExpensiveThan($price) {
        return $this->createQueryBuilder('a')
                        ->select('COUNT(a)')
                        ->where(
                                $qb->expr()->gt('a.price', $price)
                        )
                        ->getQuery()
                        ->getSingleScalarResult();
    }

}
