a2lix_translation_form:
    locale_provider: default       # [1]
    locales: %authorizedLocalesArray%          # [1-a]
    default_locale: %locale%             # [1-b]
    required_locales: [%locale%]         # [1-c]
    manager_registry: doctrine      # [2]
    templating: "A2lixTranslationFormBundle::default.html.twig"      # [3]