parameters:
    payments:
        available:
            payum:
                - paypal_express
            others:
                - balance
                - allopass
        
        allopass:
            ids: ids
            idd: idd