imports:
    - { resource: payments/paypal_express_debug.yml }
    - { resource: payments/paypal_express.yml }
    
parameters:
    payum.class_order: 'Shop\PaymentBundle\Entity\Order'
    payum.done_route: 'shop_payment_done'
    
payum:
    security:
        token_storage:
            Shop\PaymentBundle\Entity\PaymentToken: { doctrine: orm }

    storages:
        Shop\PaymentBundle\Entity\Order: { doctrine: orm }
        Shop\PaymentBundle\Entity\PaymentDetails: { doctrine: orm }

    payments:
        offline:
            offline: ~
            
        paypal_express:
            paypal_express_checkout_nvp:
                username:  %paypal_express_checkout_nvp_conf.username%
                password:  %paypal_express_checkout_nvp_conf.password%
                signature: %paypal_express_checkout_nvp_conf.signature%
                sandbox:   %paypal_express_checkout_nvp_conf.sandbox%
        
        paypal_express_debug:
            paypal_express_checkout_nvp:
                username:  %paypal_express_checkout_nvp_debug_conf.username%
                password:  %paypal_express_checkout_nvp_debug_conf.password%
                signature: %paypal_express_checkout_nvp_debug_conf.signature%
                sandbox:   %paypal_express_checkout_nvp_debug_conf.sandbox%
            