parameters:
    contact_us.general: webmaster@sinenco.com
    imprint.name: Jordan DE GEA
    imprint.address: |
        7, rue des sources
        85280, LA FERRIERE
        VENDEE, FRANCE
    imprint.siret: 752 824 441 00022
    imprint.phone: +33 6 34 38 60 63
    imprint.skype: jordan.degea
    imprint.hosting.name: OVH SAS
    imprint.hosting.address: |
         2 rue Kellermann
         59100 Roubaix
         France
    
twig:
    globals:
        invoicing_service: "@invoicing"
        currency_service: "@shop_core.currency"
        imprint:
            name: %imprint.name%
            address: %imprint.address%
            siret: %imprint.siret%
            phone: %imprint.phone%
            skype: %imprint.skype%
            hosting:
                name: %imprint.hosting.name%
                address: %imprint.hosting.address%
        invoice:
            sender_address: |
                %imprint.name%
                %imprint.siret%
                %imprint.address%
        contact_us_general: %contact_us.general%
    