services:
    
    sonata.admin.currencies:
        class: Shop\CoreBundle\Admin\CurrenciesAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "E-Commerce", label: "Currencies" }
        arguments:
            - ~
            - Shop\CoreBundle\Entity\Currencies
            - ~
        calls:
            - [ setTranslationDomain, [ShopCoreBundle]]