shop_edit_currency:
    path:     /edit_currency/{currency}
    defaults: { _controller: ShopCoreBundle:Currency:editCurrency }
    
shop_homepage:
    path:     /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: shop_product_list
        permanent: true 