services:
    shop_core.currency:
        class: Shop\CoreBundle\Services\Currency
        arguments: 
            entityManager: "@doctrine.orm.entity_manager"
            container: "@service_container"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
