sonata_admin:
    title:      Sinenco Admin
    #title_logo: bundles/acmedemo/img/fancy_acme_logo.png
    templates:
        dashboard:           SonataAdminBundle:Core:dashboard.html.twig
        layout:              %kernel.root_dir%/Resources/views/sonata_admin_base_layout.html.twig
        search:              SonataAdminBundle:Core:search.html.twig
        search_result_block: SonataAdminBundle:Block:block_search_result.html.twig
        list:                       SonataAdminBundle:CRUD:list.html.twig
        action:                     SonataAdminBundle:CRUD:action.html.twig
        select:                     SonataAdminBundle:CRUD:list__select.html.twig
        list_block:                 SonataAdminBundle:Block:block_admin_list.html.twig
        short_object_description:   SonataAdminBundle:Helper:short-object-description.html.twig
        batch:                      SonataAdminBundle:CRUD:list__batch.html.twig
        inner_list_row:             SonataAdminBundle:CRUD:list_inner_row.html.twig
        base_list_field:            SonataAdminBundle:CRUD:base_list_field.html.twig
        pager_links:                SonataAdminBundle:Pager:links.html.twig
        pager_results:              SonataAdminBundle:Pager:results.html.twig
    dashboard:
        blocks:
            -
                position: left
                type: sonata.block.project
            -
                position: left
                type: sonata.block.user
            -
                position: left
                type: sonata.admin.block.admin_list
                settings:
                    groups: [Users, Services]
            -
                position: right
                type: sonata.admin.block.admin_list
                settings:
                    groups: [ECommerce, Medias]
            -
                position: left
                type: sonata.block.service.text
                settings:
                    content: >
                        <h2>Welcome to the Sonata Admin</h2>
                        <p>This is a <code>sonata.block.service.text</code> from the Block
                        Bundle, you can create and add new block in these area by configuring
                        the <code>sonata_admin</code> section.</p> <br /> For instance, here
                        a RSS feed parser (<code>sonata.block.service.rss</code>):
            -
                position: right
                type: sonata.block.service.rss
                settings:
                    title: Sonata Project's Feeds
                    url: http://sonata-project.org/blog/archive.rss
        
        groups:
            Users:
                items:
                    - sonata.admin.user.user
                    - sonata.admin.user.address
            News:
                items:
                    - sonata.admin.blog.post
                    - sonata.admin.blog.comment
                    - sonata.admin.blog.subcomment
            Projects:
                items:
                    - sinenco.project.project
                    - sinenco.project.chatline
            Showcase:
                items:
                    - sinenco.admin.showcase.page
                    - sinenco.admin.showcase.language_page
                    - sinenco.admin.showcase.tab
                    - sinenco.admin.showcase.section
            ECommerce:
                items:
                    - sonata.admin.review
                    - sonata.admin.invoices
                    - sonata.admin.purchases
                    - sonata.admin.product
                    - sonata.admin.category
                    - sonata.admin.price
                    - sonata.admin.currencies
                    - sonata.admin.product.option
                    - sonata.admin.product.option.values
            Services:
                items:
                    - sonata.admin.service.services
                    - sonata.admin.service.detail_name
                    - sonata.admin.service.renting
            Medias:
                items:
                    - sonata.media.admin.media
         
twig:
    form:
        resources:
            - 'SonataCoreBundle:Form:datepicker.html.twig'