<?php

namespace Sinenco\ProjectBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository {

    function findOneBySpecifications($specification) {

        $query = "SELECT id FROM Project WHERE id IN(SELECT project_id FROM project_specifications WHERE file_id=:specification)";

        $connection = $this->_em->getConnection();
        $statement = $connection->prepare($query);
        $statement->bindValue('specification', $specification);
        $statement->execute();
        $results = $statement->fetchAll();

        if ( isset ( $results[0] ) ){
            return $this->find($results[0]["id"]);
        }else{
            return NULL ;
        }
    }

    function findOneByPropositions($proposition) {

        $query = "SELECT id FROM Project WHERE id IN(SELECT project_id FROM project_propositions WHERE file_id=:proposition)";

        $connection = $this->_em->getConnection();
        $statement = $connection->prepare($query);
        $statement->bindValue('proposition', $proposition);
        $statement->execute();
        $results = $statement->fetchAll();

        if ( isset ( $results[0] ) ){
            return $this->find($results[0]["id"]);
        }else{
            return NULL ;
        }
    }

}
