services:
    
    sonata.admin.invoices:
        class: Shop\PaymentBundle\Admin\InvoiceAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "E-Commerce", label: "Invoices" }
        arguments:
            - ~
            - Shop\PaymentBundle\Entity\Invoice
            - ~
        calls:
            - [ setTranslationDomain, [ShopPaymentBundle]]
            
    shop.payment.invoices_line:
        class: Shop\PaymentBundle\Admin\InvoiceLineAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "E-Commerce", label: "Invoices Line" }
        arguments:
            - ~
            - Shop\PaymentBundle\Entity\InvoiceLine
            - ~
        calls:
            - [ setTranslationDomain, [ShopPaymentBundle]]
            
    shop.payment.invoices_line_option:
        class: Shop\PaymentBundle\Admin\InvoiceLineOptionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "E-Commerce", label: "Invoices Line" }
        arguments:
            - ~
            - Shop\PaymentBundle\Entity\InvoiceLineOption
            - ~
        calls:
            - [ setTranslationDomain, [ShopPaymentBundle]]
            