services:
    invoicing:
        class: Shop\PaymentBundle\Services\InvoiceService
        arguments: 
            entityManager: "@doctrine.orm.entity_manager"
            container: "@service_container"
            
    shop.allopass.listener.callback:
        class: Shop\PaymentBundle\Listeners\AllopassCallbackListener
        arguments: 
            entityManager: "@doctrine.orm.entity_manager"
            container: "@service_container"
        tags:
            - { name: kernel.event_listener, event: "sinenco.allopasspayment.callback", method: onCallbackAllopass }

