#REST 
rest : 
    type : rest 
    resource : "routing_rest.yml"
    prefix : /api
  
#Sinenco Services
services_core:
    resource: "@ServicesCoreBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/services
    requirements:
        _locale: %authorizedLocales%


#Sinenco Bundle #
sinenco_user:
    resource: "@SinencoUserBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    requirements:
        _locale: %authorizedLocales%

#Shop Bundles #
shop_core:
    resource: "@ShopCoreBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/shop/
    requirements:
        _locale: %authorizedLocales%

shop_payment:
    resource: @ShopPaymentBundle/Resources/config/routing.yml
    prefix:   /{_locale}/shop
    requirements:
        _locale: %authorizedLocales%

shop_cart:
    resource: "@ShopCartBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/shop/cart
    requirements:
        _locale: %authorizedLocales%

shop_product:
    resource: @ShopProductBundle/Resources/config/routing.yml
    prefix:   /{_locale}/shop/
    requirements:
        _locale: %authorizedLocales%


# Payum Bundles #
payum_capture:
    resource: "@PayumBundle/Resources/config/routing/capture.xml"

payum_authorize:
    resource: "@PayumBundle/Resources/config/routing/authorize.xml"

payum_notify:
    resource: "@PayumBundle/Resources/config/routing/notify.xml"
    
# Sonata Bundles #
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

     
gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media
    
# Sinenco Core Bundle #
sinenco_core:
    resource: "@SinencoCoreBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    requirements:
        _locale: %authorizedLocales%


# FOS Bundles #
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /{_locale}/
    requirements:
        _locale: %authorizedLocales%
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /{_locale}/profile
    requirements:
        _locale: %authorizedLocales%
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /{_locale}/register
    requirements:
        _locale: %authorizedLocales%
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /{_locale}/resetting
    requirements:
        _locale: %authorizedLocales%
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /{_locale}/profile
    requirements:
        _locale: %authorizedLocales%
    
    
#Auto-redirect
root:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /%locale%/shop
        permanent: true

locale_root:
    pattern: /{_locale}/
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /%locale%/shop
        permanent: true