<?php

namespace Shop\CartBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CartItemPricesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartItemPricesRepository extends EntityRepository {
    
}
