<?php

namespace Shop\CartBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Sinenco\UserBundle\Entity\User ;

/**
 * CartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartRepository extends EntityRepository {

    public function findLastCartWithUser(User $user) {

        $qb = $this->createQueryBuilder('n');

        return $qb
                        ->where('n.user')
                        ->orderBy('n.lastUpdate', 'DESC')
                        ->setMaxResults('1')
                        ->getQuery()
                        ->getOneOrNullResult();
    }

}
