<?php

namespace Shop\ProductBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PricesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PricesRepository extends EntityRepository {
    
}
