parameters:
    
    core_service.services_available.whmcs_allopass_commission.passphrase: oNFq1xFIxbnYmcWVM2n9goV3S388bBaR
    core_service.services_available.whmcs_allopass_commission.expire: false
    core_service.services_available.whmcs_allopass_commission.renew_url: "/modules/licenses/allopass_commission.php?activation=true"
        
    core_service.services_available.whmcs_allopass.passphrase: LY99rFYjZgwpMyVrVowrbDKSnjNBoGVK
    core_service.services_available.whmcs_allopass.expire: true
    core_service.services_available.whmcs_allopass.renew_url: "/modules/licenses/allopass.php?activation=true"
        
    core_service.services_available.whmcs_allopass_credit.passphrase: ejhGBa35rgtqfUwVxLUoj5mobbv5L676
    core_service.services_available.whmcs_allopass_credit.expire: true
    core_service.services_available.whmcs_allopass_credit.renew_url: "/modules/licenses/allopass_credit.php?activation=true"
    
    core_service.services_available.whmcs_starpass.passphrase: ORfHhhUByo0LJ226zHX6tNwwvhjDkh9x
    core_service.services_available.whmcs_starpass.expire: true
    core_service.services_available.whmcs_starpass.renew_url: "/modules/licenses/starpass.php?activation=true"
       
    core_service.services_available.whmcs_movefunds.passphrase: zhhNslSLsFByrV4SYq0qDJNWKbTJyWwj
    core_service.services_available.whmcs_movefunds.expire: true
    core_service.services_available.whmcs_movefunds.renew_url: "/modules/licenses/movefunds.php?activation=true"
        
    core_service.services_available.whmcs_contribute.passphrase: 80Yf67e4H2o17zaT8DDHmBipSmzc4a62
    core_service.services_available.whmcs_contribute.expire: true
    core_service.services_available.whmcs_contribute.renew_url: "/modules/licenses/contribute.php?activation=true"
        
    core_service.services_available.hostbill_starpass.passphrase: g0KB2fZbokeNoKkr6FYvqIczfQYT3RrZ
    core_service.services_available.hostbill_starpass.expire: true
    core_service.services_available.hostbill_starpass.renew_url: "/includes/modules/licenses/starpass.php?activation=true"
        
    core_service.services_available.hostbill_movefunds.passphrase: gOYVqSAIzl80rOVIE53VWnjNNS9gO40Y
    core_service.services_available.hostbill_movefunds.expire: true
    core_service.services_available.hostbill_movefunds.renew_url: "/includes/modules/licenses/movefunds.php?activation=true"
        
    core_service.services_available.hostbill_contribute.passphrase: MqRkboFMH5O8B7NjoSHp6XT3lywzEjn
    core_service.services_available.hostbill_contribute.expire: true
    core_service.services_available.hostbill_contribute.renew_url: "/includes/modules/licenses/contribute.php?activation=true"
         
services:
    services_core.core_services:
        class: Services\CoreBundle\Services\CoreServices
        arguments: 
            entityManager: "@doctrine.orm.entity_manager"
            container: "@service_container"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            - { name: kernel.event_listener, event: sonata.admin.event.persistence.post_update, method: updateDetailsOfRentings }


    service.completeinvoice_listener:
        class:     Services\CoreBundle\Listeners\CompleteInvoiceListener
        arguments: 
            entityManager: "@doctrine.orm.entity_manager"
            container: "@service_container"
        tags:
            - { name: kernel.event_listener, event: shop.invoiceevent.complete, method: onInvoiceComplete }