parameters:
    core_service.services_available:
            whmcs_allopass_commission:
                passphrase: oNFq1xFIxbnYmcWVM2n9goV3S388bBaR
            whmcs_allopass:
                passphrase: LY99rFYjZgwpMyVrVowrbDKSnjNBoGVK
            whmcs_allopass_credit:
                passphrase: ejhGBa35rgtqfUwVxLUoj5mobbv5L676
            whmcs_starpass:
                passphrase: ORfHhhUByo0LJ226zHX6tNwwvhjDkh9x
            whmcs_movefunds:
                passphrase: zhhNslSLsFByrV4SYq0qDJNWKbTJyWwj
            whmcs_contribute:
                passphrase: 80Yf67e4H2o17zaT8DDHmBipSmzc4a62
            hostbill_movefunds:
                passphrase: gOYVqSAIzl80rOVIE53VWnjNNS9gO40Y
            hostbill_contribute:
                passphrase: MqRkboFMH5O8B7NjoSHp6XT3lywzEjn
         
services:
    services_core.core_services:
        class: Services\CoreBundle\Services\CoreServices
        arguments: 
            entityManager: "@doctrine.orm.entity_manager"
            container: "@service_container"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            - { name: kernel.event_listener, event: sonata.admin.event.persistence.post_update, method: updateDetailsOfRentings }
#        arguments: [@service_id, "plain_value", %parameter%]

    service.completeinvoice_listener:
        class:     Services\CoreBundle\Listeners\CompleteInvoiceListener
        arguments: 
            entityManager: "@doctrine.orm.entity_manager"
            container: "@service_container"
        tags:
            - { name: kernel.event_listener, event: shop.invoiceevent.complete, method: onInvoiceComplete }