services:
    
    sonata.admin.blog.post:
        class: Sinenco\BlogBundle\Admin\PostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "News", label: "Posts" }
        arguments:
            - ~
            - Sinenco\BlogBundle\Entity\Post
            - ~
        calls:
            - [ setTranslationDomain, [SinencoBlogBundle]]
            
            
    sonata.admin.blog.comment:
        class: Sinenco\BlogBundle\Admin\CommentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "News", label: "Comments" }
        arguments:
            - ~
            - Sinenco\BlogBundle\Entity\Comment
            - ~
        calls:
            - [ setTranslationDomain, [SinencoBlogBundle]]
            
            
    sonata.admin.blog.subcomment:
        class: Sinenco\BlogBundle\Admin\SubCommentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "News", label: "SubComments" }
        arguments:
            - ~
            - Sinenco\BlogBundle\Entity\SubComment
            - ~
        calls:
            - [ setTranslationDomain, [SinencoBlogBundle]]
    