services:
    
    sinenco.project.project:
        class: Sinenco\ProjectBundle\Admin\ProjectAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Project", label: "Projects" }
        arguments:
            - ~
            - Sinenco\ProjectBundle\Entity\Project
            - ~
        calls:
            - [ setTranslationDomain, [SinencoProjectBundle]]
    
    sinenco.project.chatline:
        class: Sinenco\ProjectBundle\Admin\ChatLineAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Project", label: "ChatLines" }
        arguments:
            - ~
            - Sinenco\ProjectBundle\Entity\ChatLine
            - ~
        calls:
            - [ setTranslationDomain, [SinencoProjectBundle]]
    