sinenco_project_homepage:
    path:     /
    defaults: { _controller: SinencoProjectBundle:Project:index }
    
sinenco_project_new:
    path:     /new
    defaults: { _controller: SinencoProjectBundle:Project:new }
    
sinenco_project_detail:
    path:     /detail/{id}
    defaults: { _controller: SinencoProjectBundle:Project:detail }
    requirements:
        id: \d+
        
sinenco_project_tasks:
    path:     /tasks/{id}
    defaults: { _controller: SinencoProjectBundle:Project:tasks }
    requirements:
        id: \d+
        
sinenco_project_addtask:
    path:     /addtask/{id}/{taskID}
    defaults: { _controller: SinencoProjectBundle:Project:addTask }
    requirements:
        id: \d+
        
sinenco_project_chat:
    path:     /chat/{id}
    defaults: { _controller: SinencoProjectBundle:Project:chat }
    requirements:
        id: \d+
        