sinenco_project_homepage:
    path:     /
    defaults: { _controller: SinencoProjectBundle:Project:index }
    
sinenco_project_new:
    path:     /new
    defaults: { _controller: SinencoProjectBundle:Project:new }
    
sinenco_project_detail:
    path:     /{id}
    defaults: { _controller: SinencoProjectBundle:Project:detail }
    requirements:
        id: \d+
